### PR TITLE
(MAIN) PING 3323 - Keyboard behavior on Discovery

### PR DESCRIPTION
**Pull request by agit26milan**

### CODE REVIEW

**Comment by bastian-purrer** [comment]
Image description   CodeRabbit



Currently reviewing new changes in this PR...

<details>
<summary>Commits</summary>
Files that changed from the base of the PR and between 42f961a1af1dc9132b7d405186b871ac4a3057e0 and e49e1bd9e201ee21ba4249d2fafa9f6ceaf86996 commits.
</details>

<details>
<summary>Files selected (10)</summary>

* src/components/Comments/WriteComment.js (1)
* src/hooks/core/chat/useChatUtilsHook.ts (2)
* src/hooks/screen/useChatInfoHook.ts (3)
* src/navigations/KeyboardWrapper.tsx (1)
* src/navigations/root-stack.js (5)
* src/screens/DiscoveryScreenV2/elements/DiscoveryTab.js (2)
* src/screens/DiscoveryScreenV2/elements/Search.js (3)
* src/screens/FeedScreen/index.js (2)
* src/screens/WebsocketResearchScreen/SampleChatInfoScreen.tsx (1)
* src/screens/WebsocketResearchScreen/SignedChatScreen.tsx (3)
</details>






---

**Review by bastian-purrer — COMMENTED** [review]
Image description   CodeRabbit

<details>
<summary>Commits</summary>
Files that changed from the base of the PR and between 42f961a1af1dc9132b7d405186b871ac4a3057e0 and e49e1bd9e201ee21ba4249d2fafa9f6ceaf86996 commits.
</details>

<details>
<summary>Files selected (10)</summary>

* src/components/Comments/WriteComment.js (1)
* src/hooks/core/chat/useChatUtilsHook.ts (2)
* src/hooks/screen/useChatInfoHook.ts (3)
* src/navigations/KeyboardWrapper.tsx (1)
* src/navigations/root-stack.js (5)
* src/screens/DiscoveryScreenV2/elements/DiscoveryTab.js (2)
* src/screens/DiscoveryScreenV2/elements/Search.js (3)
* src/screens/FeedScreen/index.js (2)
* src/screens/WebsocketResearchScreen/SampleChatInfoScreen.tsx (1)
* src/screens/WebsocketResearchScreen/SignedChatScreen.tsx (3)
</details>





<details>
<summary>Files not summarized due to errors (4)</summary>

* src/screens/DiscoveryScreenV2/elements/Search.js (nothing obtained from openai)
* src/screens/FeedScreen/index.js (nothing obtained from openai)
* src/screens/WebsocketResearchScreen/SampleChatInfoScreen.tsx (nothing obtained from openai)
* src/screens/WebsocketResearchScreen/SignedChatScreen.tsx (nothing obtained from openai)

</details>


<details>
<summary>Files not reviewed due to errors (6)</summary>

* src/screens/FeedScreen/index.js (no response)
* src/screens/WebsocketResearchScreen/SignedChatScreen.tsx (no response)
* src/navigations/KeyboardWrapper.tsx (no response)
* src/screens/DiscoveryScreenV2/elements/Search.js (no response)
* src/screens/WebsocketResearchScreen/SampleChatInfoScreen.tsx (no response)
* src/navigations/root-stack.js (no response)

</details>

<details>
<summary>Files skipped from review due to trivial changes (4)</summary>

* src/components/Comments/WriteComment.js
* src/hooks/core/chat/useChatUtilsHook.ts
* src/hooks/screen/useChatInfoHook.ts
* src/screens/DiscoveryScreenV2/elements/DiscoveryTab.js

</details>

<details>
<summary>Review comments generated (0)</summary>

* Review: 0
* LGTM: 0

</details>

---

<details>
<summary>Tips</summary>

### Chat with Image description  CodeRabbit Bot (`@coderabbitai`)
- Reply on review comments left by this bot to ask follow-up questions. A review comment is a comment on a diff or a file.
- Invite the bot into a review comment chain by tagging `@coderabbitai` in a reply.

### Code suggestions
- The bot may make code suggestions, but please review them carefully before committing since the line number ranges may be misaligned. 
- You can edit the comment made by the bot and manually tweak the suggestion if it is slightly off.

### Pausing incremental reviews
- Add `@coderabbitai: ignore` anywhere in the PR description to pause further reviews from the bot.

</details>

**Review by bastian-purrer — COMMENTED** [review]
Image description   CodeRabbit

<details>
<summary>Commits</summary>
Files that changed from the base of the PR and between e49e1bd9e201ee21ba4249d2fafa9f6ceaf86996 and e19679bff885c58df816e9e2a8a7f33d73f36bb0 commits.
</details>

<details>
<summary>Files selected (1)</summary>

* src/navigations/KeyboardWrapper.tsx (1)
</details>





<details>
<summary>Files not summarized due to errors (1)</summary>

* src/navigations/KeyboardWrapper.tsx (nothing obtained from openai)

</details>


<details>
<summary>Files not reviewed due to errors (1)</summary>

* src/navigations/KeyboardWrapper.tsx (no response)

</details>


<details>
<summary>Review comments generated (0)</summary>

* Review: 0
* LGTM: 0

</details>

---

<details>
<summary>Tips</summary>

### Chat with Image description  CodeRabbit Bot (`@coderabbitai`)
- Reply on review comments left by this bot to ask follow-up questions. A review comment is a comment on a diff or a file.
- Invite the bot into a review comment chain by tagging `@coderabbitai` in a reply.

### Code suggestions
- The bot may make code suggestions, but please review them carefully before committing since the line number ranges may be misaligned. 
- You can edit the comment made by the bot and manually tweak the suggestion if it is slightly off.

### Pausing incremental reviews
- Add `@coderabbitai: ignore` anywhere in the PR description to pause further reviews from the bot.

</details>

**Review by bastian-purrer — COMMENTED** [review]
Image description   CodeRabbit

<details>
<summary>Commits</summary>
Files that changed from the base of the PR and between e19679bff885c58df816e9e2a8a7f33d73f36bb0 and 0e1ebf73c3fd53970f3bab8a9e9b5ad8bce9e99b commits.
</details>

<details>
<summary>Files selected (1)</summary>

* src/screens/DiscoveryScreenV2/elements/DiscoveryTab.js (2)
</details>


<details>
<summary>Files ignored due to filter (1)</summary>

* __tests__/screens/DiscoveryScreenV2/__snapshots__/Search.test.js.snap

</details>




<details>
<summary>Files not summarized due to errors (1)</summary>

* src/screens/DiscoveryScreenV2/elements/DiscoveryTab.js (nothing obtained from openai)

</details>


<details>
<summary>Files not reviewed due to errors (1)</summary>

* src/screens/DiscoveryScreenV2/elements/DiscoveryTab.js (no response)

</details>


<details>
<summary>Review comments generated (0)</summary>

* Review: 0
* LGTM: 0

</details>

---

<details>
<summary>Tips</summary>

### Chat with Image description  CodeRabbit Bot (`@coderabbitai`)
- Reply on review comments left by this bot to ask follow-up questions. A review comment is a comment on a diff or a file.
- Invite the bot into a review comment chain by tagging `@coderabbitai` in a reply.

### Code suggestions
- The bot may make code suggestions, but please review them carefully before committing since the line number ranges may be misaligned. 
- You can edit the comment made by the bot and manually tweak the suggestion if it is slightly off.

### Pausing incremental reviews
- Add `@coderabbitai: ignore` anywhere in the PR description to pause further reviews from the bot.

</details>

**Review by fajarism — APPROVED** [review]

**Review by bastian-purrer — COMMENTED** [review]
Image description   CodeRabbit

<details>
<summary>Commits</summary>
Files that changed from the base of the PR and between 0e1ebf73c3fd53970f3bab8a9e9b5ad8bce9e99b and 7d7355a801d60b0276c7944790cbf33f0f7e9c74 commits.
</details>

<details>
<summary>Files selected (1)</summary>

* src/screens/DiscoveryScreenV2/elements/DiscoveryTab.js (3)
</details>





<details>
<summary>Files not summarized due to errors (1)</summary>

* src/screens/DiscoveryScreenV2/elements/DiscoveryTab.js (nothing obtained from openai)

</details>


<details>
<summary>Files not reviewed due to errors (1)</summary>

* src/screens/DiscoveryScreenV2/elements/DiscoveryTab.js (no response)

</details>


<details>
<summary>Review comments generated (0)</summary>

* Review: 0
* LGTM: 0

</details>

---

<details>
<summary>Tips</summary>

### Chat with Image description  CodeRabbit Bot (`@coderabbitai`)
- Reply on review comments left by this bot to ask follow-up questions. A review comment is a comment on a diff or a file.
- Invite the bot into a review comment chain by tagging `@coderabbitai` in a reply.

### Code suggestions
- The bot may make code suggestions, but please review them carefully before committing since the line number ranges may be misaligned. 
- You can edit the comment made by the bot and manually tweak the suggestion if it is slightly off.

### Pausing incremental reviews
- Add `@coderabbitai: ignore` anywhere in the PR description to pause further reviews from the bot.

</details>

**Pull request merged**
